version: '3.8'
services:
  database-api:
    container_name: database-api
    restart: always
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= postgres
volumes: 
  data: {}